#pragma once

/*
MIT License
Copyright (c) 2018 Arlen Keshabyan (arlen.albert@gmail.com)
Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

#include <algorithm>
#include <string>
#include <string_view>
#include <unordered_map>
#include "utilities.hpp"

namespace nstd::net
{
using namespace std::string_view_literals;
using nstd::utilities::case_insensitive_hash;
using nstd::utilities::case_insensitive_equal;

class media_types
{
public:
    using container_type = std::unordered_map<std::string_view, std::string_view, case_insensitive_hash, case_insensitive_equal>;

    static auto get(const std::string_view key)
    {
        const auto &[exists, it] = find(key);

        return exists ? (*it).second : decltype((*it).second)();
    }

    static std::pair<bool, typename container_type::const_iterator> find(const std::string_view key)
    {
        auto it { _media_types.find(key) };

        return  { it != std::end(_media_types), it };
    }

    const std::string_view operator[] (const std::string_view key)
    {
        return get(key);
    }

    static auto begin()
    {
        return std::begin(_media_types);
    }

    static auto end()
    {
        return std::end(_media_types);
    }

    static auto size()
    {
        return std::size(_media_types);
    }

protected:

    inline static container_type _media_types
    {
        { "1d-interleaved-parityfec"sv, "application/1d-interleaved-parityfec"sv },
        { "3gpdash-qoe-report+xml"sv, "application/3gpdash-qoe-report+xml"sv },
        { "3gpp-ims+xml"sv, "application/3gpp-ims+xml"sv },
        { "A2L"sv, "application/A2L"sv },
        { "activemessage"sv, "application/activemessage"sv },
        { "activemessage"sv, "application/activemessage"sv },
        { "activity+json"sv, "application/activity+json"sv },
        { "alto-costmap+json"sv, "application/alto-costmap+json"sv },
        { "alto-costmapfilter+json"sv, "application/alto-costmapfilter+json"sv },
        { "alto-directory+json"sv, "application/alto-directory+json"sv },
        { "alto-endpointprop+json"sv, "application/alto-endpointprop+json"sv },
        { "alto-endpointpropparams+json"sv, "application/alto-endpointpropparams+json"sv },
        { "alto-endpointcost+json"sv, "application/alto-endpointcost+json"sv },
        { "alto-endpointcostparams+json"sv, "application/alto-endpointcostparams+json"sv },
        { "alto-error+json"sv, "application/alto-error+json"sv },
        { "alto-networkmapfilter+json"sv, "application/alto-networkmapfilter+json"sv },
        { "alto-networkmap+json"sv, "application/alto-networkmap+json"sv },
        { "AML"sv, "application/AML"sv },
        { "andrew-inset"sv, "application/andrew-inset"sv },
        { "applefile"sv, "application/applefile"sv },
        { "ATF"sv, "application/ATF"sv },
        { "ATFX"sv, "application/ATFX"sv },
        { "atom+xml"sv, "application/atom+xml"sv },
        { "atomcat+xml"sv, "application/atomcat+xml"sv },
        { "atomdeleted+xml"sv, "application/atomdeleted+xml"sv },
        { "atomicmail"sv, "application/atomicmail"sv },
        { "atomsvc+xml"sv, "application/atomsvc+xml"sv },
        { "ATXML"sv, "application/ATXML"sv },
        { "auth-policy+xml"sv, "application/auth-policy+xml"sv },
        { "bacnet-xdd+zip"sv, "application/bacnet-xdd+zip"sv },
        { "batch-SMTP"sv, "application/batch-SMTP"sv },
        { "beep+xml"sv, "application/beep+xml"sv },
        { "calendar+json"sv, "application/calendar+json"sv },
        { "calendar+xml"sv, "application/calendar+xml"sv },
        { "call-completion"sv, "application/call-completion"sv },
        { "CALS-1840"sv, "application/CALS-1840"sv },
        { "cbor"sv, "application/cbor"sv },
        { "cccex"sv, "application/cccex"sv },
        { "ccmp+xml"sv, "application/ccmp+xml"sv },
        { "ccxml+xml"sv, "application/ccxml+xml"sv },
        { "CDFX+XML"sv, "application/CDFX+XML"sv },
        { "cdmi-capability"sv, "application/cdmi-capability"sv },
        { "cdmi-container"sv, "application/cdmi-container"sv },
        { "cdmi-domain"sv, "application/cdmi-domain"sv },
        { "cdmi-object"sv, "application/cdmi-object"sv },
        { "cdmi-queue"sv, "application/cdmi-queue"sv },
        { "cdni"sv, "application/cdni"sv },
        { "CEA"sv, "application/CEA"sv },
        { "cea-2018+xml"sv, "application/cea-2018+xml"sv },
        { "cellml+xml"sv, "application/cellml+xml"sv },
        { "cfw"sv, "application/cfw"sv },
        { "clue_info+xml"sv, "application/clue_info+xml"sv },
        { "cms"sv, "application/cms"sv },
        { "cnrp+xml"sv, "application/cnrp+xml"sv },
        { "coap-group+json"sv, "application/coap-group+json"sv },
        { "coap-payload"sv, "application/coap-payload"sv },
        { "commonground"sv, "application/commonground"sv },
        { "conference-info+xml"sv, "application/conference-info+xml"sv },
        { "cpl+xml"sv, "application/cpl+xml"sv },
        { "cose"sv, "application/cose"sv },
        { "cose-key"sv, "application/cose-key"sv },
        { "cose-key-set"sv, "application/cose-key-set"sv },
        { "csrattrs"sv, "application/csrattrs"sv },
        { "csta+xml"sv, "application/csta+xml"sv },
        { "CSTAdata+xml"sv, "application/CSTAdata+xml"sv },
        { "csvm+json"sv, "application/csvm+json"sv },
        { "cwt"sv, "application/cwt"sv },
        { "cybercash"sv, "application/cybercash"sv },
        { "dash+xml"sv, "application/dash+xml"sv },
        { "dashdelta"sv, "application/dashdelta"sv },
        { "davmount+xml"sv, "application/davmount+xml"sv },
        { "dca-rft"sv, "application/dca-rft"sv },
        { "DCD"sv, "application/DCD"sv },
        { "dec-dx"sv, "application/dec-dx"sv },
        { "dialog-info+xml"sv, "application/dialog-info+xml"sv },
        { "dicom"sv, "application/dicom"sv },
        { "dicom+json"sv, "application/dicom+json"sv },
        { "dicom+xml"sv, "application/dicom+xml"sv },
        { "DII"sv, "application/DII"sv },
        { "DIT"sv, "application/DIT"sv },
        { "dns"sv, "application/dns"sv },
        { "dns+json"sv, "application/dns+json"sv },
        { "dns-message"sv, "application/dns-message"sv },
        { "dskpp+xml"sv, "application/dskpp+xml"sv },
        { "dssc+der"sv, "application/dssc+der"sv },
        { "dssc+xml"sv, "application/dssc+xml"sv },
        { "dvcs"sv, "application/dvcs"sv },
        { "ecmascript"sv, "application/ecmascript"sv },
        { "EDI-consent"sv, "application/EDI-consent"sv },
        { "EDIFACT"sv, "application/EDIFACT"sv },
        { "EDI-X12"sv, "application/EDI-X12"sv },
        { "efi"sv, "application/efi"sv },
        { "EmergencyCallData.Comment+xml"sv, "application/EmergencyCallData.Comment+xml"sv },
        { "EmergencyCallData.Control+xml"sv, "application/EmergencyCallData.Control+xml"sv },
        { "EmergencyCallData.DeviceInfo+xml"sv, "application/EmergencyCallData.DeviceInfo+xml"sv },
        { "EmergencyCallData.eCall.MSD"sv, "application/EmergencyCallData.eCall.MSD"sv },
        { "EmergencyCallData.ProviderInfo+xml"sv, "application/EmergencyCallData.ProviderInfo+xml"sv },
        { "EmergencyCallData.ServiceInfo+xml"sv, "application/EmergencyCallData.ServiceInfo+xml"sv },
        { "EmergencyCallData.SubscriberInfo+xml"sv, "application/EmergencyCallData.SubscriberInfo+xml"sv },
        { "EmergencyCallData.VEDS+xml"sv, "application/EmergencyCallData.VEDS+xml"sv },
        { "emma+xml"sv, "application/emma+xml"sv },
        { "emotionml+xml"sv, "application/emotionml+xml"sv },
        { "encaprtp"sv, "application/encaprtp"sv },
        { "epp+xml"sv, "application/epp+xml"sv },
        { "epub+zip"sv, "application/epub+zip"sv },
        { "eshop"sv, "application/eshop"sv },
        { "example"sv, "application/example"sv },
        { "exi"sv, "application/exi"sv },
        { "fastinfoset"sv, "application/fastinfoset"sv },
        { "fastsoap"sv, "application/fastsoap"sv },
        { "fdt+xml"sv, "application/fdt+xml"sv },
        { "fhir+json"sv, "application/fhir+json"sv },
        { "fhir+xml"sv, "application/fhir+xml"sv },
        { "fits"sv, "application/fits"sv },
        { "font-sfnt - DEPRECATED in favor of font/sfnt"sv, "application/font-sfnt"sv },
        { "font-tdpfr"sv, "application/font-tdpfr"sv },
        { "font-woff - DEPRECATED in favor of font/woff"sv, "application/font-woff"sv },
        { "framework-attributes+xml"sv, "application/framework-attributes+xml"sv },
        { "geo+json"sv, "application/geo+json"sv },
        { "geo+json-seq"sv, "application/geo+json-seq"sv },
        { "geopackage+sqlite3"sv, "application/geopackage+sqlite3"sv },
        { "geoxacml+xml"sv, "application/geoxacml+xml"sv },
        { "gltf-buffer"sv, "application/gltf-buffer"sv },
        { "gml+xml"sv, "application/gml+xml"sv },
        { "gzip"sv, "application/gzip"sv },
        { "H224"sv, "application/H224"sv },
        { "held+xml"sv, "application/held+xml"sv },
        { "http"sv, "application/http"sv },
        { "hyperstudio"sv, "application/hyperstudio"sv },
        { "ibe-key-request+xml"sv, "application/ibe-key-request+xml"sv },
        { "ibe-pkg-reply+xml"sv, "application/ibe-pkg-reply+xml"sv },
        { "ibe-pp-data"sv, "application/ibe-pp-data"sv },
        { "iges"sv, "application/iges"sv },
        { "im-iscomposing+xml"sv, "application/im-iscomposing+xml"sv },
        { "index"sv, "application/index"sv },
        { "index.cmd"sv, "application/index.cmd"sv },
        { "index.obj"sv, "application/index.obj"sv },
        { "index.response"sv, "application/index.response"sv },
        { "index.vnd"sv, "application/index.vnd"sv },
        { "inkml+xml"sv, "application/inkml+xml"sv },
        { "IOTP"sv, "application/IOTP"sv },
        { "ipfix"sv, "application/ipfix"sv },
        { "ipp"sv, "application/ipp"sv },
        { "isup"sv, "application/isup"sv },
        { "its+xml"sv, "application/its+xml"sv },
        { "javascript"sv, "application/javascript"sv },
        { "js"sv, "application/javascript"sv },
        { "jf2feed+json"sv, "application/jf2feed+json"sv },
        { "jose"sv, "application/jose"sv },
        { "jose+json"sv, "application/jose+json"sv },
        { "jrd+json"sv, "application/jrd+json"sv },
        { "json"sv, "application/json"sv },
        { "json-patch+json"sv, "application/json-patch+json"sv },
        { "json-seq"sv, "application/json-seq"sv },
        { "jwk+json"sv, "application/jwk+json"sv },
        { "jwk-set+json"sv, "application/jwk-set+json"sv },
        { "jwt"sv, "application/jwt"sv },
        { "kpml-request+xml"sv, "application/kpml-request+xml"sv },
        { "kpml-response+xml"sv, "application/kpml-response+xml"sv },
        { "ld+json"sv, "application/ld+json"sv },
        { "lgr+xml"sv, "application/lgr+xml"sv },
        { "link-format"sv, "application/link-format"sv },
        { "load-control+xml"sv, "application/load-control+xml"sv },
        { "lost+xml"sv, "application/lost+xml"sv },
        { "lostsync+xml"sv, "application/lostsync+xml"sv },
        { "LXF"sv, "application/LXF"sv },
        { "mac-binhex40"sv, "application/mac-binhex40"sv },
        { "macwriteii"sv, "application/macwriteii"sv },
        { "mads+xml"sv, "application/mads+xml"sv },
        { "marc"sv, "application/marc"sv },
        { "marcxml+xml"sv, "application/marcxml+xml"sv },
        { "mathematica"sv, "application/mathematica"sv },
        { "mathml-content+xml"sv, "application/mathml-content+xml"sv },
        { "mathml-presentation+xml"sv, "application/mathml-presentation+xml"sv },
        { "mathml+xml"sv, "application/mathml+xml"sv },
        { "mbms-associated-procedure-description+xml"sv, "application/mbms-associated-procedure-description+xml"sv },
        { "mbms-deregister+xml"sv, "application/mbms-deregister+xml"sv },
        { "mbms-envelope+xml"sv, "application/mbms-envelope+xml"sv },
        { "mbms-msk-response+xml"sv, "application/mbms-msk-response+xml"sv },
        { "mbms-msk+xml"sv, "application/mbms-msk+xml"sv },
        { "mbms-protection-description+xml"sv, "application/mbms-protection-description+xml"sv },
        { "mbms-reception-report+xml"sv, "application/mbms-reception-report+xml"sv },
        { "mbms-register-response+xml"sv, "application/mbms-register-response+xml"sv },
        { "mbms-register+xml"sv, "application/mbms-register+xml"sv },
        { "mbms-schedule+xml"sv, "application/mbms-schedule+xml"sv },
        { "mbms-user-service-description+xml"sv, "application/mbms-user-service-description+xml"sv },
        { "mbox"sv, "application/mbox"sv },
        { "media_control+xml"sv, "application/media_control+xml"sv },
        { "media-policy-dataset+xml"sv, "application/media-policy-dataset+xml"sv },
        { "mediaservercontrol+xml"sv, "application/mediaservercontrol+xml"sv },
        { "merge-patch+json"sv, "application/merge-patch+json"sv },
        { "metalink4+xml"sv, "application/metalink4+xml"sv },
        { "mets+xml"sv, "application/mets+xml"sv },
        { "MF4"sv, "application/MF4"sv },
        { "mikey"sv, "application/mikey"sv },
        { "mmt-usd+xml"sv, "application/mmt-usd+xml"sv },
        { "mods+xml"sv, "application/mods+xml"sv },
        { "moss-keys"sv, "application/moss-keys"sv },
        { "moss-signature"sv, "application/moss-signature"sv },
        { "mosskey-data"sv, "application/mosskey-data"sv },
        { "mosskey-request"sv, "application/mosskey-request"sv },
        { "mp21"sv, "application/mp21"sv },
        { "mp4"sv, "application/mp4"sv },
        { "mpeg4-generic"sv, "application/mpeg4-generic"sv },
        { "mpeg4-iod"sv, "application/mpeg4-iod"sv },
        { "mpeg4-iod-xmt"sv, "application/mpeg4-iod-xmt"sv },
        { "mrb-consumer+xml"sv, "application/mrb-consumer+xml"sv },
        { "mrb-publish+xml"sv, "application/mrb-publish+xml"sv },
        { "msc-ivr+xml"sv, "application/msc-ivr+xml"sv },
        { "msc-mixer+xml"sv, "application/msc-mixer+xml"sv },
        { "msword"sv, "application/msword"sv },
        { "mud+json"sv, "application/mud+json"sv },
        { "mxf"sv, "application/mxf"sv },
        { "n-quads"sv, "application/n-quads"sv },
        { "n-triples"sv, "application/n-triples"sv },
        { "nasdata"sv, "application/nasdata"sv },
        { "news-checkgroups"sv, "application/news-checkgroups"sv },
        { "news-groupinfo"sv, "application/news-groupinfo"sv },
        { "news-transmission"sv, "application/news-transmission"sv },
        { "nlsml+xml"sv, "application/nlsml+xml"sv },
        { "node"sv, "application/node"sv },
        { "nss"sv, "application/nss"sv },
        { "ocsp-request"sv, "application/ocsp-request"sv },
        { "ocsp-response"sv, "application/ocsp-response"sv },
        { "octet-stream"sv, "application/octet-stream"sv },
        { "ODA"sv, "application/ODA"sv },
        { "odm+xml"sv, "application/odm+xml"sv },
        { "ODX"sv, "application/ODX"sv },
        { "oebps-package+xml"sv, "application/oebps-package+xml"sv },
        { "ogg"sv, "application/ogg"sv },
        { "oxps"sv, "application/oxps"sv },
        { "p2p-overlay+xml"sv, "application/p2p-overlay+xml"sv },
        { "parityfec"sv, "application/parityfec"sv },
        { "passport"sv, "application/passport"sv },
        { "patch-ops-error+xml"sv, "application/patch-ops-error+xml"sv },
        { "pdf"sv, "application/pdf"sv },
        { "PDX"sv, "application/PDX"sv },
        { "pgp-encrypted"sv, "application/pgp-encrypted"sv },
        { "pgp-keys"sv, "application/pgp-keys"sv },
        { "pgp-signature"sv, "application/pgp-signature"sv },
        { "pidf-diff+xml"sv, "application/pidf-diff+xml"sv },
        { "pidf+xml"sv, "application/pidf+xml"sv },
        { "pkcs10"sv, "application/pkcs10"sv },
        { "pkcs7-mime"sv, "application/pkcs7-mime"sv },
        { "pkcs7-signature"sv, "application/pkcs7-signature"sv },
        { "pkcs8"sv, "application/pkcs8"sv },
        { "pkcs8-encrypted"sv, "application/pkcs8-encrypted"sv },
        { "pkcs12"sv, "application/pkcs12"sv },
        { "pkix-attr-cert"sv, "application/pkix-attr-cert"sv },
        { "pkix-cert"sv, "application/pkix-cert"sv },
        { "pkix-crl"sv, "application/pkix-crl"sv },
        { "pkix-pkipath"sv, "application/pkix-pkipath"sv },
        { "pkixcmp"sv, "application/pkixcmp"sv },
        { "pls+xml"sv, "application/pls+xml"sv },
        { "poc-settings+xml"sv, "application/poc-settings+xml"sv },
        { "postscript"sv, "application/postscript"sv },
        { "ppsp-tracker+json"sv, "application/ppsp-tracker+json"sv },
        { "problem+json"sv, "application/problem+json"sv },
        { "problem+xml"sv, "application/problem+xml"sv },
        { "provenance+xml"sv, "application/provenance+xml"sv },
        { "prs.alvestrand.titrax-sheet"sv, "application/prs.alvestrand.titrax-sheet"sv },
        { "prs.cww"sv, "application/prs.cww"sv },
        { "prs.hpub+zip"sv, "application/prs.hpub+zip"sv },
        { "prs.nprend"sv, "application/prs.nprend"sv },
        { "prs.plucker"sv, "application/prs.plucker"sv },
        { "prs.rdf-xml-crypt"sv, "application/prs.rdf-xml-crypt"sv },
        { "prs.xsf+xml"sv, "application/prs.xsf+xml"sv },
        { "pskc+xml"sv, "application/pskc+xml"sv },
        { "rdf+xml"sv, "application/rdf+xml"sv },
        { "route-apd+xml"sv, "application/route-apd+xml"sv },
        { "route-s-tsid+xml"sv, "application/route-s-tsid+xml"sv },
        { "route-usd+xml"sv, "application/route-usd+xml"sv },
        { "QSIG"sv, "application/QSIG"sv },
        { "raptorfec"sv, "application/raptorfec"sv },
        { "rdap+json"sv, "application/rdap+json"sv },
        { "reginfo+xml"sv, "application/reginfo+xml"sv },
        { "relax-ng-compact-syntax"sv, "application/relax-ng-compact-syntax"sv },
        { "remote-printing"sv, "application/remote-printing"sv },
        { "reputon+json"sv, "application/reputon+json"sv },
        { "resource-lists-diff+xml"sv, "application/resource-lists-diff+xml"sv },
        { "resource-lists+xml"sv, "application/resource-lists+xml"sv },
        { "rfc+xml"sv, "application/rfc+xml"sv },
        { "riscos"sv, "application/riscos"sv },
        { "rlmi+xml"sv, "application/rlmi+xml"sv },
        { "rls-services+xml"sv, "application/rls-services+xml"sv },
        { "rpki-ghostbusters"sv, "application/rpki-ghostbusters"sv },
        { "rpki-manifest"sv, "application/rpki-manifest"sv },
        { "rpki-publication"sv, "application/rpki-publication"sv },
        { "rpki-roa"sv, "application/rpki-roa"sv },
        { "rpki-updown"sv, "application/rpki-updown"sv },
        { "rtf"sv, "application/rtf"sv },
        { "rtploopback"sv, "application/rtploopback"sv },
        { "rtx"sv, "application/rtx"sv },
        { "samlassertion+xml"sv, "application/samlassertion+xml"sv },
        { "samlmetadata+xml"sv, "application/samlmetadata+xml"sv },
        { "sbml+xml"sv, "application/sbml+xml"sv },
        { "scaip+xml"sv, "application/scaip+xml"sv },
        { "scim+json"sv, "application/scim+json"sv },
        { "scvp-cv-request"sv, "application/scvp-cv-request"sv },
        { "scvp-cv-response"sv, "application/scvp-cv-response"sv },
        { "scvp-vp-request"sv, "application/scvp-vp-request"sv },
        { "scvp-vp-response"sv, "application/scvp-vp-response"sv },
        { "sdp"sv, "application/sdp"sv },
        { "secevent+jwt"sv, "application/secevent+jwt"sv },
        { "senml-exi"sv, "application/senml-exi"sv },
        { "senml+cbor"sv, "application/senml+cbor"sv },
        { "senml+json"sv, "application/senml+json"sv },
        { "senml+xml"sv, "application/senml+xml"sv },
        { "sensml-exi"sv, "application/sensml-exi"sv },
        { "sensml+cbor"sv, "application/sensml+cbor"sv },
        { "sensml+json"sv, "application/sensml+json"sv },
        { "sensml+xml"sv, "application/sensml+xml"sv },
        { "sep-exi"sv, "application/sep-exi"sv },
        { "sep+xml"sv, "application/sep+xml"sv },
        { "session-info"sv, "application/session-info"sv },
        { "set-payment"sv, "application/set-payment"sv },
        { "set-payment-initiation"sv, "application/set-payment-initiation"sv },
        { "set-registration"sv, "application/set-registration"sv },
        { "set-registration-initiation"sv, "application/set-registration-initiation"sv },
        { "sgml"sv, "application/sgml"sv },
        { "sgml-open-catalog"sv, "application/sgml-open-catalog"sv },
        { "shf+xml"sv, "application/shf+xml"sv },
        { "sieve"sv, "application/sieve"sv },
        { "simple-filter+xml"sv, "application/simple-filter+xml"sv },
        { "simple-message-summary"sv, "application/simple-message-summary"sv },
        { "simpleSymbolContainer"sv, "application/simpleSymbolContainer"sv },
        { "slate"sv, "application/slate"sv },
        { "smil+xml"sv, "application/smil+xml"sv },
        { "smpte336m"sv, "application/smpte336m"sv },
        { "soap+fastinfoset"sv, "application/soap+fastinfoset"sv },
        { "soap+xml"sv, "application/soap+xml"sv },
        { "sparql-query"sv, "application/sparql-query"sv },
        { "sparql-results+xml"sv, "application/sparql-results+xml"sv },
        { "spirits-event+xml"sv, "application/spirits-event+xml"sv },
        { "sql"sv, "application/sql"sv },
        { "srgs"sv, "application/srgs"sv },
        { "srgs+xml"sv, "application/srgs+xml"sv },
        { "sru+xml"sv, "application/sru+xml"sv },
        { "stix+json"sv, "application/stix+json"sv },
        { "ssml+xml"sv, "application/ssml+xml"sv },
        { "tamp-apex-update"sv, "application/tamp-apex-update"sv },
        { "tamp-apex-update-confirm"sv, "application/tamp-apex-update-confirm"sv },
        { "tamp-community-update"sv, "application/tamp-community-update"sv },
        { "tamp-community-update-confirm"sv, "application/tamp-community-update-confirm"sv },
        { "tamp-error"sv, "application/tamp-error"sv },
        { "tamp-sequence-adjust"sv, "application/tamp-sequence-adjust"sv },
        { "tamp-sequence-adjust-confirm"sv, "application/tamp-sequence-adjust-confirm"sv },
        { "tamp-status-query"sv, "application/tamp-status-query"sv },
        { "tamp-status-response"sv, "application/tamp-status-response"sv },
        { "tamp-update"sv, "application/tamp-update"sv },
        { "tamp-update-confirm"sv, "application/tamp-update-confirm"sv },
        { "taxii+json"sv, "application/taxii+json"sv },
        { "tei+xml"sv, "application/tei+xml"sv },
        { "thraud+xml"sv, "application/thraud+xml"sv },
        { "timestamp-query"sv, "application/timestamp-query"sv },
        { "timestamp-reply"sv, "application/timestamp-reply"sv },
        { "timestamped-data"sv, "application/timestamped-data"sv },
        { "tlsrpt+gzip"sv, "application/tlsrpt+gzip"sv },
        { "tlsrpt+json"sv, "application/tlsrpt+json"sv },
        { "tnauthlist"sv, "application/tnauthlist"sv },
        { "trickle-ice-sdpfrag"sv, "application/trickle-ice-sdpfrag"sv },
        { "trig"sv, "application/trig"sv },
        { "ttml+xml"sv, "application/ttml+xml"sv },
        { "tve-trigger"sv, "application/tve-trigger"sv },
        { "tzif"sv, "application/tzif"sv },
        { "tzif-leap"sv, "application/tzif-leap"sv },
        { "ulpfec"sv, "application/ulpfec"sv },
        { "urc-grpsheet+xml"sv, "application/urc-grpsheet+xml"sv },
        { "urc-ressheet+xml"sv, "application/urc-ressheet+xml"sv },
        { "urc-targetdesc+xml"sv, "application/urc-targetdesc+xml"sv },
        { "urc-uisocketdesc+xml"sv, "application/urc-uisocketdesc+xml"sv },
        { "vcard+json"sv, "application/vcard+json"sv },
        { "vcard+xml"sv, "application/vcard+xml"sv },
        { "vemmi"sv, "application/vemmi"sv },
        { "voicexml+xml"sv, "application/voicexml+xml"sv },
        { "voucher-cms+json"sv, "application/voucher-cms+json"sv },
        { "vq-rtcpxr"sv, "application/vq-rtcpxr"sv },
        { "watcherinfo+xml"sv, "application/watcherinfo+xml"sv },
        { "webpush-options+json"sv, "application/webpush-options+json"sv },
        { "whoispp-query"sv, "application/whoispp-query"sv },
        { "whoispp-response"sv, "application/whoispp-response"sv },
        { "widget"sv, "application/widget"sv },
        { "wita"sv, "application/wita"sv },
        { "wordperfect5.1"sv, "application/wordperfect5.1"sv },
        { "wsdl+xml"sv, "application/wsdl+xml"sv },
        { "wspolicy+xml"sv, "application/wspolicy+xml"sv },
        { "x-www-form-urlencoded"sv, "application/x-www-form-urlencoded"sv },
        { "x400-bp"sv, "application/x400-bp"sv },
        { "xacml+xml"sv, "application/xacml+xml"sv },
        { "xcap-att+xml"sv, "application/xcap-att+xml"sv },
        { "xcap-caps+xml"sv, "application/xcap-caps+xml"sv },
        { "xcap-diff+xml"sv, "application/xcap-diff+xml"sv },
        { "xcap-el+xml"sv, "application/xcap-el+xml"sv },
        { "xcap-error+xml"sv, "application/xcap-error+xml"sv },
        { "xcap-ns+xml"sv, "application/xcap-ns+xml"sv },
        { "xcon-conference-info-diff+xml"sv, "application/xcon-conference-info-diff+xml"sv },
        { "xcon-conference-info+xml"sv, "application/xcon-conference-info+xml"sv },
        { "xenc+xml"sv, "application/xenc+xml"sv },
        { "xhtml+xml"sv, "application/xhtml+xml"sv },
        { "xliff+xml"sv, "application/xliff+xml"sv },
        { "xml"sv, "application/xml"sv },
        { "xml-dtd"sv, "application/xml-dtd"sv },
        { "xml-external-parsed-entity"sv, "application/xml-external-parsed-entity"sv },
        { "xml-patch+xml"sv, "application/xml-patch+xml"sv },
        { "xmpp+xml"sv, "application/xmpp+xml"sv },
        { "xop+xml"sv, "application/xop+xml"sv },
        { "xslt+xml"sv, "application/xslt+xml"sv },
        { "xv+xml"sv, "application/xv+xml"sv },
        { "yang"sv, "application/yang"sv },
        { "yang-data+json"sv, "application/yang-data+json"sv },
        { "yang-data+xml"sv, "application/yang-data+xml"sv },
        { "yang-patch+json"sv, "application/yang-patch+json"sv },
        { "yang-patch+xml"sv, "application/yang-patch+xml"sv },
        { "yin+xml"sv, "application/yin+xml"sv },
        { "zip"sv, "application/zip"sv },
        { "zlib"sv, "application/zlib"sv },
        { "zstd"sv, "application/zstd"sv },
        { "1d-interleaved-parityfec"sv, "audio/1d-interleaved-parityfec"sv },
        { "32kadpcm"sv, "audio/32kadpcm"sv },
        { "3gpp"sv, "audio/3gpp"sv },
        { "3gpp2"sv, "audio/3gpp2"sv },
        { "aac"sv, "audio/aac"sv },
        { "ac3"sv, "audio/ac3"sv },
        { "AMR"sv, "audio/AMR"sv },
        { "AMR-WB"sv, "audio/AMR-WB"sv },
        { "amr-wb+"sv, "audio/amr-wb+"sv },
        { "aptx"sv, "audio/aptx"sv },
        { "asc"sv, "audio/asc"sv },
        { "ATRAC-ADVANCED-LOSSLESS"sv, "audio/ATRAC-ADVANCED-LOSSLESS"sv },
        { "ATRAC-X"sv, "audio/ATRAC-X"sv },
        { "ATRAC3"sv, "audio/ATRAC3"sv },
        { "basic"sv, "audio/basic"sv },
        { "BV16"sv, "audio/BV16"sv },
        { "BV32"sv, "audio/BV32"sv },
        { "clearmode"sv, "audio/clearmode"sv },
        { "CN"sv, "audio/CN"sv },
        { "DAT12"sv, "audio/DAT12"sv },
        { "dls"sv, "audio/dls"sv },
        { "dsr-es201108"sv, "audio/dsr-es201108"sv },
        { "dsr-es202050"sv, "audio/dsr-es202050"sv },
        { "dsr-es202211"sv, "audio/dsr-es202211"sv },
        { "dsr-es202212"sv, "audio/dsr-es202212"sv },
        { "DV"sv, "audio/DV"sv },
        { "DVI4"sv, "audio/DVI4"sv },
        { "eac3"sv, "audio/eac3"sv },
        { "encaprtp"sv, "audio/encaprtp"sv },
        { "EVRC"sv, "audio/EVRC"sv },
        { "EVRC-QCP"sv, "audio/EVRC-QCP"sv },
        { "EVRC0"sv, "audio/EVRC0"sv },
        { "EVRC1"sv, "audio/EVRC1"sv },
        { "EVRCB"sv, "audio/EVRCB"sv },
        { "EVRCB0"sv, "audio/EVRCB0"sv },
        { "EVRCB1"sv, "audio/EVRCB1"sv },
        { "EVRCNW"sv, "audio/EVRCNW"sv },
        { "EVRCNW0"sv, "audio/EVRCNW0"sv },
        { "EVRCNW1"sv, "audio/EVRCNW1"sv },
        { "EVRCWB"sv, "audio/EVRCWB"sv },
        { "EVRCWB0"sv, "audio/EVRCWB0"sv },
        { "EVRCWB1"sv, "audio/EVRCWB1"sv },
        { "EVS"sv, "audio/EVS"sv },
        { "example"sv, "audio/example"sv },
        { "fwdred"sv, "audio/fwdred"sv },
        { "G711-0"sv, "audio/G711-0"sv },
        { "G719"sv, "audio/G719"sv },
        { "G7221"sv, "audio/G7221"sv },
        { "G722"sv, "audio/G722"sv },
        { "G723"sv, "audio/G723"sv },
        { "G726-16"sv, "audio/G726-16"sv },
        { "G726-24"sv, "audio/G726-24"sv },
        { "G726-32"sv, "audio/G726-32"sv },
        { "G726-40"sv, "audio/G726-40"sv },
        { "G728"sv, "audio/G728"sv },
        { "G729"sv, "audio/G729"sv },
        { "G7291"sv, "audio/G7291"sv },
        { "G729D"sv, "audio/G729D"sv },
        { "G729E"sv, "audio/G729E"sv },
        { "GSM"sv, "audio/GSM"sv },
        { "GSM-EFR"sv, "audio/GSM-EFR"sv },
        { "GSM-HR-08"sv, "audio/GSM-HR-08"sv },
        { "iLBC"sv, "audio/iLBC"sv },
        { "ip-mr_v2.5"sv, "audio/ip-mr_v2.5"sv },
        { "L8"sv, "audio/L8"sv },
        { "L16"sv, "audio/L16"sv },
        { "L20"sv, "audio/L20"sv },
        { "L24"sv, "audio/L24"sv },
        { "LPC"sv, "audio/LPC"sv },
        { "MELP"sv, "audio/MELP"sv },
        { "MELP600"sv, "audio/MELP600"sv },
        { "MELP1200"sv, "audio/MELP1200"sv },
        { "MELP2400"sv, "audio/MELP2400"sv },
        { "mobile-xmf"sv, "audio/mobile-xmf"sv },
        { "MPA"sv, "audio/MPA"sv },
        { "mp4"sv, "audio/mp4"sv },
        { "MP4A-LATM"sv, "audio/MP4A-LATM"sv },
        { "mpa-robust"sv, "audio/mpa-robust"sv },
        { "mpeg"sv, "audio/mpeg"sv },
        { "mpeg4-generic"sv, "audio/mpeg4-generic"sv },
        { "ogg"sv, "audio/ogg"sv },
        { "opus"sv, "audio/opus"sv },
        { "parityfec"sv, "audio/parityfec"sv },
        { "PCMA"sv, "audio/PCMA"sv },
        { "PCMA-WB"sv, "audio/PCMA-WB"sv },
        { "PCMU"sv, "audio/PCMU"sv },
        { "PCMU-WB"sv, "audio/PCMU-WB"sv },
        { "prs.sid"sv, "audio/prs.sid"sv },
        { "QCELP"sv, "audio/QCELP"sv },
        { "raptorfec"sv, "audio/raptorfec"sv },
        { "RED"sv, "audio/RED"sv },
        { "rtp-enc-aescm128"sv, "audio/rtp-enc-aescm128"sv },
        { "rtploopback"sv, "audio/rtploopback"sv },
        { "rtp-midi"sv, "audio/rtp-midi"sv },
        { "rtx"sv, "audio/rtx"sv },
        { "SMV"sv, "audio/SMV"sv },
        { "SMV0"sv, "audio/SMV0"sv },
        { "SMV-QCP"sv, "audio/SMV-QCP"sv },
        { "sp-midi"sv, "audio/sp-midi"sv },
        { "speex"sv, "audio/speex"sv },
        { "t140c"sv, "audio/t140c"sv },
        { "t38"sv, "audio/t38"sv },
        { "telephone-event"sv, "audio/telephone-event"sv },
        { "TETRA_ACELP"sv, "audio/TETRA_ACELP"sv },
        { "tone"sv, "audio/tone"sv },
        { "UEMCLIP"sv, "audio/UEMCLIP"sv },
        { "ulpfec"sv, "audio/ulpfec"sv },
        { "usac"sv, "audio/usac"sv },
        { "VDVI"sv, "audio/VDVI"sv },
        { "VMR-WB"sv, "audio/VMR-WB"sv },
        { "vorbis"sv, "audio/vorbis"sv },
        { "vorbis-config"sv, "audio/vorbis-config"sv },
        { "collection"sv, "font/collection"sv },
        { "otf"sv, "font/otf"sv },
        { "sfnt"sv, "font/sfnt"sv },
        { "ttf"sv, "font/ttf"sv },
        { "woff"sv, "font/woff"sv },
        { "woff2"sv, "font/woff2"sv },
        { "aces"sv, "image/aces"sv },
        { "avci"sv, "image/avci"sv },
        { "avcs"sv, "image/avcs"sv },
        { "bmp"sv, "image/bmp"sv },
        { "cgm"sv, "image/cgm"sv },
        { "dicom-rle"sv, "image/dicom-rle"sv },
        { "emf"sv, "image/emf"sv },
        { "example"sv, "image/example"sv },
        { "fits"sv, "image/fits"sv },
        { "g3fax"sv, "image/g3fax"sv },
        { "gif"sv, "image/gif"sv },
        { "heic"sv, "image/heic"sv },
        { "heic-sequence"sv, "image/heic-sequence"sv },
        { "heif"sv, "image/heif"sv },
        { "heif-sequence"sv, "image/heif-sequence"sv },
        { "ief"sv, "image/ief"sv },
        { "jls"sv, "image/jls"sv },
        { "jp2"sv, "image/jp2"sv },
        { "jpeg"sv, "image/jpeg"sv },
        { "jpg"sv, "image/jpeg"sv },
        { "jpm"sv, "image/jpm"sv },
        { "jpx"sv, "image/jpx"sv },
        { "ktx"sv, "image/ktx"sv },
        { "naplps"sv, "image/naplps"sv },
        { "png"sv, "image/png"sv },
        { "prs.btif"sv, "image/prs.btif"sv },
        { "prs.pti"sv, "image/prs.pti"sv },
        { "pwg-raster"sv, "image/pwg-raster"sv },
        { "svg+xml"sv, "image/svg+xml"sv },
        { "svg"sv, "image/svg+xml"sv },
        { "t38"sv, "image/t38"sv },
        { "tif"sv, "image/tiff"sv },
        { "tiff"sv, "image/tiff"sv },
        { "tiff-fx"sv, "image/tiff-fx"sv },
        { "wmf"sv, "image/wmf"sv },
        { "x-emf - DEPRECATED in favor of image/emf"sv, "image/emf"sv },
        { "x-wmf - DEPRECATED in favor of image/wmf"sv, "image/wmf"sv },
        { "CPIM"sv, "message/CPIM"sv },
        { "delivery-status"sv, "message/delivery-status"sv },
        { "disposition-notification"sv, "message/disposition-notification"sv },
        { "example"sv, "message/example"sv },
        { "external-body"sv, "message/external-body"sv },
        { "feedback-report"sv, "message/feedback-report"sv },
        { "global"sv, "message/global"sv },
        { "global-delivery-status"sv, "message/global-delivery-status"sv },
        { "global-disposition-notification"sv, "message/global-disposition-notification"sv },
        { "global-headers"sv, "message/global-headers"sv },
        { "http"sv, "message/http"sv },
        { "imdn+xml"sv, "message/imdn+xml"sv },
        { "partial"sv, "message/partial"sv },
        { "rfc822"sv, "message/rfc822"sv },
        { "s-http"sv, "message/s-http"sv },
        { "sip"sv, "message/sip"sv },
        { "sipfrag"sv, "message/sipfrag"sv },
        { "tracking-status"sv, "message/tracking-status"sv },
        { "3mf"sv, "model/3mf"sv },
        { "example"sv, "model/example"sv },
        { "gltf-binary"sv, "model/gltf-binary"sv },
        { "gltf+json"sv, "model/gltf+json"sv },
        { "iges"sv, "model/iges"sv },
        { "mesh"sv, "message/mesh"sv },
        { "stl"sv, "model/stl"sv },
        { "vrml"sv, "model/vrml"sv },
        { "x3d-vrml"sv, "model/x3d-vrml"sv },
        { "x3d+fastinfoset"sv, "model/x3d+fastinfoset"sv },
        { "x3d+xml"sv, "model/x3d+xml"sv },
        { "alternative"sv, "model/alternative"sv },
        { "appledouble"sv, "multipart/appledouble"sv },
        { "byteranges"sv, "multipart/byteranges"sv },
        { "digest"sv, "multipart/digest"sv },
        { "encrypted"sv, "multipart/encrypted"sv },
        { "example"sv, "multipart/example"sv },
        { "form-data"sv, "multipart/form-data"sv },
        { "header-set"sv, "multipart/header-set"sv },
        { "mixed"sv, "multipart/mixed"sv },
        { "multilingual"sv, "multipart/multilingual"sv },
        { "parallel"sv, "multipart/parallel"sv },
        { "related"sv, "multipart/related"sv },
        { "report"sv, "multipart/report"sv },
        { "signed"sv, "multipart/signed"sv },
        { "voice-message"sv, "multipart/voice-message"sv },
        { "x-mixed-replace"sv, "multipart/x-mixed-replace"sv },
        { "1d-interleaved-parityfec"sv, "text/1d-interleaved-parityfec"sv },
        { "cache-manifest"sv, "text/cache-manifest"sv },
        { "calendar"sv, "text/calendar"sv },
        { "css"sv, "text/css"sv },
        { "csv"sv, "text/csv"sv },
        { "csv-schema"sv, "text/csv-schema"sv },
        { "directory - DEPRECATED by RFC6350"sv, "text/directory"sv },
        { "dns"sv, "text/dns"sv },
        { "encaprtp"sv, "text/encaprtp"sv },
        { "enriched"sv, "text/enriched"sv },
        { "example"sv, "text/example"sv },
        { "fwdred"sv, "text/fwdred"sv },
        { "grammar-ref-list"sv, "text/grammar-ref-list"sv },
        { "html"sv, "text/html"sv },
        { "htm"sv, "text/html"sv },
        { "jcr-cnd"sv, "text/jcr-cnd"sv },
        { "markdown"sv, "text/markdown"sv },
        { "mizar"sv, "text/mizar"sv },
        { "n3"sv, "text/n3"sv },
        { "parameters"sv, "text/parameters"sv },
        { "parityfec"sv, "text/parityfec"sv },
        { "plain"sv, "text/plain"sv },
        { "provenance-notation"sv, "text/provenance-notation"sv },
        { "prs.fallenstein.rst"sv, "text/prs.fallenstein.rst"sv },
        { "prs.lines.tag"sv, "text/prs.lines.tag"sv },
        { "prs.prop.logic"sv, "text/prs.prop.logic"sv },
        { "raptorfec"sv, "text/raptorfec"sv },
        { "RED"sv, "text/RED"sv },
        { "rfc822-headers"sv, "text/rfc822-headers"sv },
        { "richtext"sv, "text/richtext"sv },
        { "rtf"sv, "text/rtf"sv },
        { "rtp-enc-aescm128"sv, "text/rtp-enc-aescm128"sv },
        { "rtploopback"sv, "text/rtploopback"sv },
        { "rtx"sv, "text/rtx"sv },
        { "sgml"sv, "text/sgml"sv },
        { "strings"sv, "text/strings"sv },
        { "t140"sv, "text/t140"sv },
        { "tab-separated-values"sv, "text/tab-separated-values"sv },
        { "text"sv, "text/plain"sv },
        { "txt"sv, "text/plain"sv },
        { "troff"sv, "text/troff"sv },
        { "turtle"sv, "text/turtle"sv },
        { "ulpfec"sv, "text/ulpfec"sv },
        { "uri-list"sv, "text/uri-list"sv },
        { "vcard"sv, "text/vcard"sv },
        { "xml"sv, "text/xml"sv },
        { "xml-external-parsed-entity"sv, "text/xml-external-parsed-entity"sv },
        { "1d-interleaved-parityfec"sv, "video/1d-interleaved-parityfec"sv },
        { "3gpp"sv, "video/3gpp"sv },
        { "3gpp2"sv, "video/3gpp2"sv },
        { "3gpp-tt"sv, "video/3gpp-tt"sv },
        { "BMPEG"sv, "video/BMPEG"sv },
        { "BT656"sv, "video/BT656"sv },
        { "CelB"sv, "video/CelB"sv },
        { "DV"sv, "video/DV"sv },
        { "encaprtp"sv, "video/encaprtp"sv },
        { "example"sv, "video/example"sv },
        { "H261"sv, "video/H261"sv },
        { "H263"sv, "video/H263"sv },
        { "H263-1998"sv, "video/H263-1998"sv },
        { "H263-2000"sv, "video/H263-2000"sv },
        { "H264"sv, "video/H264"sv },
        { "H264-RCDO"sv, "video/H264-RCDO"sv },
        { "H264-SVC"sv, "video/H264-SVC"sv },
        { "H265"sv, "video/H265"sv },
        { "iso.segment"sv, "video/iso.segment"sv },
        { "JPEG"sv, "video/JPEG"sv },
        { "jpeg2000"sv, "video/jpeg2000"sv },
        { "mj2"sv, "video/mj2"sv },
        { "MP1S"sv, "video/MP1S"sv },
        { "MP2P"sv, "video/MP2P"sv },
        { "MP2T"sv, "video/MP2T"sv },
        { "mp4"sv, "video/mp4"sv },
        { "MP4V-ES"sv, "video/MP4V-ES"sv },
        { "MPV"sv, "video/MPV"sv },
        { "mpeg"sv, "video/mpeg"sv },
        { "mpeg4-generic"sv, "video/mpeg4-generic"sv },
        { "nv"sv, "video/nv"sv },
        { "ogg"sv, "video/ogg"sv },
        { "parityfec"sv, "video/parityfec"sv },
        { "pointer"sv, "video/pointer"sv },
        { "quicktime"sv, "video/quicktime"sv },
        { "raptorfec"sv, "video/raptorfec"sv },
        { "raw"sv, "video/raw"sv },
        { "rtp-enc-aescm128"sv, "video/rtp-enc-aescm128"sv },
        { "rtploopback"sv, "video/rtploopback"sv },
        { "rtx"sv, "video/rtx"sv },
        { "smpte291"sv, "video/smpte291"sv },
        { "SMPTE292M"sv, "video/SMPTE292M"sv },
        { "ulpfec"sv, "video/ulpfec"sv },
        { "vc1"sv, "video/vc1"sv },
        { "vc2"sv, "video/vc2"sv },
        { "VP8"sv, "video/VP8"sv },
        { "VP9"sv, "video/VP9"sv }
    };
};

}
